### ISSUE TITLE
Selection items in visual editor don't show text description

### ISSUE THREAD

**Issue by kuchel77** [mattieha/select-list-card#3]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v1.0.0
**Last working release (if known):**

**Browser and Operating System:**

Firefox (77.0.1) and Safari (v??)  on MacOS Catalina 

**Description of problem:**
![Screen Shot 2020-07-06 at 10 15 23 am](https://user-images.githubusercontent.com/52343790/86545472-98dcb700-bf72-11ea-9f4d-81214f253c98.png)
<img width="858" alt="Screen Shot 2020-07-06 at 10 26 54 am" src="https://user-images.githubusercontent.com/52343790/86545608-3cc66280-bf73-11ea-8a06-ccbedf4e12ab.png">

The text for "Truncate long option name" and "Selected option always in view" are missing from next to the selection buttons. This occurs both in Firefox and Safari (Firefox on top, Safari below with different screen sizes). If I change the screen size, it still doesn't show up. 

There is an error that comes up with the first card selection as well as when I choose the 'Custom: Select List Card' which is 

```
TypeError: t.path is undefined select-list-card.js:280:123
```

**Additional information:**

**Comment by mattieha** [comment]
Thank you for the bug report.

I don't own a mac so hopefully I can borrow one this weekend to reproduce your bug.
On windows Firefox(78.0.1) the text appears just fine, I used the default <ha-switch> component for the toggles so its weird why text doesn't show. Do you have any other custom cards with toggles in the editor, so you can confirm it's only broken in my card?

The TypeError seems to be unrelated, I have a better solution for getting the path now so I'll make a new release today.

**Comment by mattieha** [comment]
I just released [v1.1.0](https://github.com/mattieha/select-list-card/releases/tag/v1.1.0) please update the card via hacs and let me know if this fixes the TypeError.

**Comment by willsmarthome** [comment]
> **Checklist:**
> 
> * [x]  I updated to the latest version available
> * [x]  I cleared the cache of my browser
> 
> **Release with the issue:**
> v1.0.0
> **Last working release (if known):**
> 
> **Browser and Operating System:**
> 
> Firefox (77.0.1) and Safari (v??) on MacOS Catalina
> 
> **Description of problem:**
> ![Screen Shot 2020-07-06 at 10 15 23 am](https://user-images.githubusercontent.com/52343790/86545472-98dcb700-bf72-11ea-9f4d-81214f253c98.png)
> <img alt="Screen Shot 2020-07-06 at 10 26 54 am" width="858" src="https://user-images.githubusercontent.com/52343790/86545608-3cc66280-bf73-11ea-8a06-ccbedf4e12ab.png">
> 
> The text for "Truncate long option name" and "Selected option always in view" are missing from next to the selection buttons. This occurs both in Firefox and Safari (Firefox on top, Safari below with different screen sizes). If I change the screen size, it still doesn't show up.
> 
> There is an error that comes up with the first card selection as well as when I choose the 'Custom: Select List Card' which is
> 
> ```
> TypeError: t.path is undefined select-list-card.js:280:123
> ```
> 
> **Additional information:**

Same Here, also with Firefox.

![Aantekening 2020-07-07 084143](https://user-images.githubusercontent.com/65604497/86842778-fd4c6300-c0a5-11ea-9d83-6f5fac76752d.jpg)

**Comment by kuchel77** [comment]
Same issue still unfortunately. I check on Firefox with a disabled cache to make sure I was getting the latest version, as well as Chrome, which I haven't used previously with this instance of Home Assistant, and still the same issue. I also tested on a Windows PC with both Firefox and Chrome and it also shows the same.

When I have a look at the source, it seems that the label is there, but it isn't displaying for some reason. 

The path error is no longer appearing using 1.1.1.

**Comment by nagyrobi** [comment]
Same error here, missing descriptions.
Could it be because our locale is not English, and the card config is trying to load the corresponding locale but doesn't find it?

**Comment by mattieha** [comment]
First of all my apologies for the late response: work and holidays.

Apparently there has been some changes in the HA frontend code since 0.112.0 which I only upgraded too. That's why i couldn't reproduce the bug you all have been reporting.
I'm still figuring out why it happens and how to correctly use the `ha-switch` component, since there isn't any documentation for it.

For now I have made a fix which places the label outside toggle button. The label is now showing, although it's not clickable, so you have to click the toggle itself.

Please update to [v1.2.0](https://github.com/mattieha/select-list-card/releases/tag/v1.2.0) and let me know if this fixes the problem.

**Comment by nagyrobi** [comment]
Thanks. 
Now for me (at least in Hungarian) the first and the third switch have the same text.

**Comment by mattieha** [comment]
You're right, I copied the localize string and forgot to change it.

I'll release a bug fix tomorrow, thanks for letting me know!
